# Generated by Django 4.1.5 on 2023-01-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='name_en',
            field=models.CharField(default='', max_length=100),
        ),
    ]
